---
title: "Untitled"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
building_data = read.csv('data/data_train.csv', header = TRUE)
zipcode_data = read.csv('building-permit-applications-data/zipcode_data_all.csv', header = TRUE)
```

```{r}
library(tidyverse)
library(tigris)
library(ggmap)
library(zipcode)
data(zipcode)

# SF zipcodes start with 94XXX
zips_sf <- zctas(cb = T, starts_with = c("94"), class = "sf") %>%
  select(zip = ZCTA5CE10, geometry)

head(zips_sf)
```
```{r}

basemap <- get_map(location = c(lon = -122.3999, lat = 37.7846), zoom = 9)

ggmap(basemap) +
  geom_sf(aes(fill = zip), data = zips_sf, inherit.aes = F, size = 0, alpha = 0.6) +
  coord_sf(ndiscr = F) +
  theme(legend.position = "none")
```
```{r}

basemap <- get_map(location = c(lon = -122.3999, lat = 37.7846), zoom = 12)

zips = zipcode[zipcode$zip %in% building_data$Zipcode, ]
zips$Zipcode = zips$zip

total <- merge(zips, zipcode_data, by="Zipcode")

fin_heatmap <- ggmap(basemap, extent = "device") + stat_summary_2d(data = total, aes(x = longitude, y = latitude, z = Business.total), fun = mean, alpha = 0.6, bins = 30) + scale_fill_gradient(name = "Businesses", low = "green", high = "red")
fin_heatmap

fin_heatmap <- ggmap(basemap, extent = "device") + stat_summary_2d(data = total, aes(x = longitude, y = latitude, z = Restaurant.total), fun = mean, alpha = 0.6, bins = 30) + scale_fill_gradient(name = "Restaurants", low = "green", high = "red")
fin_heatmap

fin_heatmap <- ggmap(basemap, extent = "device") + stat_summary_2d(data = total, aes(x = longitude, y = latitude, z = Fire.total), fun = mean, alpha = 0.6, bins = 30) + scale_fill_gradient(name = "Fires", low = "green", high = "red")
fin_heatmap

permit_counts_df = data.frame("Zipcode"=c(94102.0, 94103.0, 94104.0, 94105.0, 94107.0, 94108.0, 94109.0, 94110.0, 94111.0, 94112.0, 94114.0, 94115.0, 94116.0, 94117.0, 94118.0, 94121.0, 94122.0, 94123.0, 94124.0, 94127.0, 94129.0, 94130.0, 94131.0, 94132.0, 94133.0, 94134.0, 94158.0), "PermitCount"=c(5750, 8813, 3384, 6963, 6200, 4187, 8982, 14228, 4325, 6303, 10699, 8096, 5149, 9424, 7878, 6189, 7142, 7592, 4205, 4059, 20, 61, 6130, 2801, 5920, 2395, 865))

total <- merge(zips, permit_counts_df, by="Zipcode")

fin_heatmap <- ggmap(basemap, extent = "device") + stat_summary_2d(data = total, aes(x = longitude, y = latitude, z = PermitCount), fun = mean, alpha = 0.6, bins = 30) + scale_fill_gradient(name = "Building Permits", low = "green", high = "red")
fin_heatmap
```